-- Continuous Integration
-- Continuous Deploymment

name: Simple CI

on:
  push:
    branches:
      - main

jobs:
  aymans-job:
    runs-on: ubuntu-latest

    steps:
    - name: step 1
      run: ls -a

    - name: step 2
      run: mkdir ayman 
   
    - name: step 3
      run: ls -a